import argparse
import json
from pathlib import Path
from typing import Any


def load_manifest(manifest_path: Path) -> dict[str, Any]:
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def render_repo_context(manifest: dict[str, Any], repo: dict[str, Any]) -> str:
    workspace = manifest.get("workspace", {})
    source_of_truth = workspace.get("sourceOfTruthRepo", "fleet-command")
    branch_types = manifest.get("branchTypes", [])
    branch_shorthand = "/".join(branch_type["id"] for branch_type in branch_types)
    completion_flow = manifest.get("completionFlow", {})
    lines = [
        f"# {repo['name']} Workspace Context",
        "",
        "> DO NOT EDIT. Generated from `fleet-command/workspace/workspace.manifest.json`.",
        "",
        "## Summary",
        "",
        f"- Workspace: `{workspace.get('name', 'workspace')}`",
        f"- Source of truth: `{source_of_truth}`",
        f"- Repo role: `{repo['role']}`",
        f"- Purpose: {repo['purpose']}",
        "",
        "## Read First",
        "",
    ]

    for key_file in repo.get("keyFiles", []):
        lines.append(f"- `{key_file}`")

    lines.extend(
        [
            "",
            "## Verification",
            "",
        ]
    )

    commands = repo.get("commands", {})
    for category, values in commands.items():
        lines.append(f"- `{category}`")
        for value in values:
            lines.append(f"  - `{value}`")

    policies = manifest.get("policies", [])
    if policies:
        lines.extend(
            [
                "",
                "## Workspace Policies",
                "",
            ]
        )
        for policy in policies:
            lines.append(f"- {policy['title']}: {policy['rule']}")

    if completion_flow:
        lines.extend(
            [
                "",
                "## Completion Reminder",
                "",
                f"- Before finishing work, follow the completion flow in `{completion_flow['sourceDoc']}`.",
                f"- Organize branches by work type using `{branch_shorthand}`.",
                "- For one cross-repo task, keep the same slug across repos.",
                "- Python work uses `uv` for dependency management and execution.",
            ]
        )
        for step in completion_flow.get("summary", []):
            lines.append(f"- {step}")

    notes = manifest.get("workspace", {}).get("notes", [])
    if notes:
        lines.extend(
            [
                "",
                "## Workspace Notes",
                "",
            ]
        )
        for note in notes:
            lines.append(f"- {note}")

    lines.append("")
    return "\n".join(lines)


def render_rgignore(patterns: list[str]) -> str:
    lines = [
        "# Generated by fleet-command/scripts/render_workspace_assets.py",
        "# Workspace-level ripgrep ignore rules for high-noise paths.",
        "",
    ]
    lines.extend(patterns)
    lines.append("")
    return "\n".join(lines)


def _write_or_check(target_path: Path, expected: str, check: bool) -> bool:
    if check:
        if not target_path.exists():
            return False
        current = target_path.read_text(encoding="utf-8")
        return current == expected

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(expected, encoding="utf-8")
    return True


def render_workspace_assets(manifest_path: Path, check: bool = False) -> bool:
    manifest_path = manifest_path.resolve()
    manifest = load_manifest(manifest_path)
    workspace_root = manifest_path.parents[2]
    is_clean = True

    for repo in manifest["repos"]:
        repo_root = workspace_root / repo["path"]
        context_path = repo_root / repo["generatedContextPath"]
        expected = render_repo_context(manifest, repo)
        is_clean = _write_or_check(context_path, expected, check) and is_clean

    rgignore_path = workspace_root / manifest["workspace"]["rootRgignorePath"]
    rgignore = render_rgignore(manifest["ignore"]["patterns"])
    is_clean = _write_or_check(rgignore_path, rgignore, check) and is_clean
    return is_clean


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render workspace context and ignore assets from the workspace manifest.")
    parser.add_argument(
        "--manifest",
        default=str(Path(__file__).resolve().parents[1] / "workspace" / "workspace.manifest.json"),
        help="Path to workspace.manifest.json",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether generated assets are up to date without writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    is_clean = render_workspace_assets(Path(args.manifest), check=args.check)
    if args.check:
        if is_clean:
            print("workspace assets are up to date")
            return 0
        print("workspace assets are out of date")
        return 1
    print("workspace assets rendered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
